### ISSUE TITLE
Add a basic virtual joy-stick to make the mobile version usable.

### ISSUE THREAD

**Issue by LOGANLEEE** [kevinshen56714/SkyOffice#23]
thanks in advance

**Comment by kevinshen56714** [comment]
Thank you for the idea! We're still working on adding more features to the PC version (chat, private rooms, etc). Making it work on mobile browsers could be the next step after those. That said, feel free to contribute or share more thoughts!

**Comment by DaxChen** [comment]
Hey Logan, thanks for the interest in contributing, any help is extremely appreciated!
I think we can start with something basic and add things gradually along the way. Having a virtual joy-stick to move around sounds like a reasonable first step. Please don't hesitate to share your thoughts and let us know if you need any help!

**Comment by kevinshen56714** [comment]
Thanks to @jga-dev, we now have a joystick for mobile usage :)
