### ISSUE TITLE
BUG: High cpu usage

### ISSUE THREAD

**Issue by idodav** [kevinshen56714/SkyOffice#35]
Me and my friends entered a private skyoffice room. And the computer worked like crazy. 
After closing the tab the computer worked normally.
The image is from an ubuntu system. It also happened on mac big sur.
![image](https://user-images.githubusercontent.com/21335259/150100504-8b19cee2-2650-458a-be5b-0469fe5fc665.png)

**Comment by kevinshen56714** [comment]
Thanks for testing this. Could you provide me some more details of your use case for me to pinpoint the issue?

What browser are you using? How many people are in the room? Did you and your friends have video on? Were you screen sharing at the same time?

Thanks!

**Comment by kevinshen56714** [comment]
Closing this as we have just done client side refactoring. Let me know if this is still an issue.
