### ISSUE TITLE
Front end not responding

### ISSUE THREAD

**Issue by swaticolab** [kevinshen56714/SkyOffice#39]
HI,

The project looks great. When I try to start the server using "npm run start" , I do not see any screen launching..
![image](https://user-images.githubusercontent.com/49306345/157177792-ed460951-17f4-4378-97ec-68ef0420ac74.png)

It is just stuck at this screen.

**Comment by kevinshen56714** [comment]
Thanks for trying out SkyOffice. That is because you also need to start a client instance. Go to the ```client``` folder, and do ```npm install``` and ```npm run start```

**Comment by swaticolab** [comment]
Thanks @kevinshen56714. It worked. My mistake.
One basic question though. how do other users join the same lobby as mine, to begin the interaction in virtual world?
